// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnxpbprjxhskmintscol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNueHBicHJqeGhza21pbnRzY29sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5Nzk0NTgsImV4cCI6MjA2NzU1NTQ1OH0.mlN5wXAXpY23yzBATV9fsp0yDd29GGI7zuYZOtmyMHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});